### PR TITLE
2020.06.01, use github tarball, split outputs, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.
  * took some care to dig into the various files... they're long and full of stuff, but do have the license text in them

Notes:
- thanks for packaging this!
- this PR:
  - updates to `2020.06.01`
  - uses the upstream github tarball, so it should get updated automatically
  - splits out the different locales, named after the upstream
    - the build could probably have been in bash, but i'm tired
  - maintains the `hunspell-en` as a metapackage
  - proposes myself as a maintainer

### CODE REVIEW

**Comment by bollwyvl** [comment]
Hm, I might have been getting my local dictionaries, as tests were working fine. I guess hooray tests!

There's also this, which collects a lot of dictionaries in a lot of locales, with licenses, might be worth looking into:

https://github.com/wooorm/dictionaries

**Comment by scopatz** [comment]
Wow, amazing.... Let me know when it passes!

**Comment by bollwyvl** [comment]
@scopatz looks like we're good!

**Comment by scopatz** [comment]
Super!

**Comment by bollwyvl** [comment]
Thanks!

**Pull request merged**
